### ISSUE TITLE
Support for writing to basic text files

### ISSUE THREAD

**Issue by sierret** [metapensiero/metapensiero.pj#76]
Is it possible to add support for writing to files? Currently yields Transformation error. 
Reading from files may also be an option as well.

Eg.
                        with open(file, 'a') as f:
                            f.writelines(["timestamp","event at timestamp"])
                        f.close()

**Comment by azazel75** [comment]
Indentation aside,  this code is wrong. The role of the `with` statement in Python is to take care of closing it, so in this case `f` it's already closed when it reaches line 3. I cannot look into it now, but from what I remember it's the `with`  statement which isn't implemented, because there isn't a similar statement in JS. Anyway, I think you can translate code like this:

```python
f = open(file, 'a'):
f.writelines(["timestamp","event at timestamp"])
f.close()
```

**Comment by sierret** [comment]
Ah. I see. Got it thanks. Appreciate the noob assistance.
